name: Publish

on: push

jobs:
  publish:
    name: Publish reveal.js slides
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pip install vtk-osmesa --index-url https://gitlab.kitware.com/api/v4/projects/13/packages/pypi/simple # needed for the CI to run
      - run: sudo apt update -qy && sudo apt install ffmpeg -qy
      - run: jupyter nbconvert *.ipynb --to slides --execute
      - run: |
          mkdir dist
          mv README.md dist/index.md
          mv *.slides.html dist/.
      - run: cp *.xml dist/.
      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to gh-pages
        with:
          branch: gh-pages
          folder: dist
          single-commit: true
